題目:
array1 = np.array([[10, 8], [3, 5]]) 

- 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
- 運用上列array計算特徵值、特徵向量?
- 運用上列array計算SVD?

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

In [3]:
array1_inverse = np.linalg.inv(array1)
array1_inverse

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [4]:
array1 * array1_inverse #不是單位矩陣

array([[ 1.92307692, -2.46153846],
       [-0.34615385,  1.92307692]])

In [5]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)

In [6]:
#特徵值為
w

array([13.,  2.])

In [7]:
#特徵向量為
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [9]:
#3. 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))